mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    path('check/', views.check, name='check'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib import admin


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.question_text
    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently?',
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text
    

mysite/polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from django.urls import reverse
# from django.views.generic.detail import DetailView

from .models import Choice, Question

def index(request):
    context={}
    template = loader.get_template('polls/index.html')
    return HttpResponse(template.render(context, request))

def check(request):
    q=Question.objects.all()
    context={'question':q}
    template = loader.get_template('polls/check.html')
    return HttpResponse(template.render(context, request))

# geneic view는 URL에서 캡처된 기본 키 값이 "pk"라고 기대하기 때문에
# question_id를 generic view를 위해 pk로 변경
# 기본적으로 DetailView generic view는 <app name>/<model name>_detail.html
# 템플릿을 사용 => "polls/question_detail.html"

# 위가 장고의 일반적인 뷰, 아래는 이해를 위한 뷰
# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     template = loader.get_template('polls/index.html')
#     context = {
#         'latest_question_list': latest_question_list,
#     }
#     return HttpResponse(template.render(context, request))

# 모든 뷰에 render() 적용할 시, loader와 HttpResponse를 import하지 않아도 됨.
# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     context = {'latest_question_list': latest_question_list}
#     return render(request, 'polls/index.html', context)


# Leave the rest of the views (detail, results, vote) unchanged

# class CheckView(generic.DetailView):
#     model = Question
#     template_name = 'polls/check.html'

# class DetailView(generic.DetailView):
#     model = Question
#     template_name = 'polls/detail.html'

# 위가 장고의 일반적인 뷰, 아래는 이해를 위한 뷰
# def detail(request, question_id):
#     try:
#         question = Question.objects.get(pk=question_id)
#     except Question.DoesNotExist:
#         raise Http404("question does not exist")
#     return render(request, 'polls/detail.html', {'question': question})

# from django.shortcuts import get_object_or_404
# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/detail.html', {'question': question})

# get_object_or_404 처럼 동작하는 get_list_or_404 함수도 존재함
# get() 대신 filter()를 쓰는 것만 다름.(리스트가 비어있을 경우 Http404)

# class ResultsView(generic.DetailView):
#     model = Question
#     template_name = 'polls/results.html'

# 위가 장고의 일반적인 뷰, 아래는 이해를 위한 뷰
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    selected_choice = question.choice_set.get(pk=request.POST['choice'])
    selected_choice.votes += 1
    selected_choice.save()
    # POST data가 잘 처리되었으면 언제나 HttpResponseRedirect를 줘서
    # 유저가 뒤로 가기 버튼을 눌렀을 때 2번 전송되는 것을 방지함
    return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

# request.POST의 값은 항상 문자열들임.
# reverse() 함수는 뷰 함수에서 URL을 하드코딩하지 않도록 도와줌.

mysite/polls/templates/polls/base.html
{% load static %}
<!doctype html>
<html class="no-js" lang="ko">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>부대 당도 측정기</title>
      <!-- Compressed CSS --> 
      
<link rel="stylesheet" href="{% static 'css/foundation.css' %}"> 
<link rel="stylesheet" href="{% static 'css/style1.css' %}">
      
      
<!-- Compressed JavaScript -->
<script src="{% static 'js/foundation.js' %}"></script>
  </head>
  <body>
    <!-- Start Top Bar -->
<header id="header" class="topbar-sticky-shrink-header"></header>
      
<div data-sticky-container>
    <div
        data-sticky
        data-margin-top="0"
        data-top-anchor="header:bottom"
        data-btm-anchor="content:bottom"
    >
        <div class="top-bar topbar-sticky-shrink">
            <div class="top-bar-title">
                <img src="https://placehold.it/150x38" alt="(꿀)" />
                <span>군생활 당도 측정기</span>
            </div>
            <div class="top-bar-right">
                <ul class="menu">
                    <li><a href="#">당도 측정</a></li>
                    <li><a href="#">당도 분포</a></li>
                    <li><a href="#">피드백</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="column row" id="content"></div>
      
<!-- <nav class="top-bar topbar-responsive">
  <div class="top-bar-title">
    <span data-responsive-toggle="topbar-responsive" data-hide-for="medium">
      <button class="menu-icon" type="button" data-toggle></button>
    </span>
    <a class="topbar-responsive-logo" href="#"><strong>군생활 당도 측정기</strong></a>
  </div>
  <div id="topbar-responsive" class="topbar-responsive-links">
    <div class="top-bar-right">
      <ul class="menu simple vertical medium-horizontal">
        <li><a href="#">Home</a></li>
        <li><a href="#">About</a></li>
        <li><a href="#">Services</a></li>
        <li><a href="#">Works</a></li>
        <li><a href="#">News</a></li>
        <li><a href="#">Contact</a></li>
        <li>
          <button type="button" class="button hollow topbar-responsive-button">Categories</button>
        </li>
      </ul>
    </div>
  </div>
</nav>
 -->

      
<!-- End Top Bar -->

    {% block content %}
    {% endblock %}
      
    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="https://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.js"></script>
    <script>
      $(document).foundation();
    </script>
  </body>
</html>

mysite/polls/templates/polls/check.html
{% extends 'polls/base.html' %}

{% block content %}

<div class="container">
        <form action="{% url 'polls:vote' question.id %}" method="post">
            {% csrf_token %}
            {% for q in question %}
                <div class="card" style="margin: 20px 0;">
                    <div class="card-body">
                        <h4 class="card-title">{{forloop.counter}}) {{ q.question_text }}</h4>
                        {% for choice in q.choice_set.all %}
                            <input type="radio" name="{{forloop.parentloop.counter}}" id="choice{{ choice.id }}" value="{{ choice.id }}" required />
                            <label for="choice{{ choice.id }}">{{ choice.choice_text }}</label><br />
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
            <div class="d-flex justify-content-end" style="margin: 40px 0;">
                <input type="submit" class="btn btn-danger btn-lg" value="Submit" />
            </div>
            
        </form>
</div>

{% endblock %}

mysite/polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block content %}

<div class="row column text-center">    
    <div class="row">
         <div class="small-12 medium-3 columns">
           <img src="/static/img/fff.png"/>
         </div>
        <br>
         <div class="small-12 medium-9 columns">
          <div class="hero-slider-slide-content">
            <h3>군생활 당도 측정기</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus commodo consectetur arcu ut aliquam. Nullam rhoncus tellus dolor, eu mollis libero suscipit at. Mauris imperdiet aliquam consectetur. Curabitur ac massa dapibus, viverra neque eu, lacinia nisi.</p>
            <div>
              <button class="hollow button" type="button"><img src="https://placehold.it/20x20"/> 
                  <a href="{% url 'polls:check' %}">측정 시작하기</a>
                </button>
            </div>
          </div>
        </div>
      </div>
  </div>



{% endblock %}